[[prefacio]]
[preface]
== Prefácio

Esse curso de Desenho e Topografia busca introduzir noções de topografia de
maneira simples e concisa. Para isso buscou-se usar o mínimo possível de conceitos
matemáticos. Evitou-se o uso da trigonometria e da geometria analítica, baseando-se
quase que exclusivamente em geometria plana.

Com a mesma intenção foi usado o processo gráfico, aplicado a figuras geométricas
desenhadas em escala, para o cálculo de áreas. Atividade bastante comum em
topografia.

Esse módulo foi montado para ser um material de referência, no qual o aluno
possa buscar informações para resolução de exercícios, aplicados pelo professor
durante o desenvolvimento do curso.

Na confecção desse módulo o autor foi apenas um selecionador de material,
acrescentando algumas pequenas contribuições, no intuito de tornar a leitura mais
clara. Buscou-se citar, na lista de Referências Bibliográficas, todas as referências
utilizadas.

Espera-se que esse material possa despertar o interesse dos alunos pela
Topografia, uma ciência há muito tempo praticada, mas sempre atual.

Desejo a todos vocês: Boa sorte!

____
Prof. Alexandre José Soares Miná +
Bananeiras – PB, Junho de 2009.
____
